apiVersion: v1
kind: Secret
metadata:
  name: termostat-trigger-secrets
type: Opaque
data:
  TUYA_ACCESS_ID: {{ .Values.secrets.TUYA_ACCESS_ID | b64enc | quote }}
  TUYA_ACCESS_KEY: {{ .Values.secrets.TUYA_ACCESS_KEY | b64enc | quote }}
  API_KEY: {{ .Values.secrets.API_KEY | b64enc | quote }}
