apiVersion: v1
kind: Service
metadata:
  name: trigger-temp
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.port }}
      targetPort: 30003
  selector:
    app: trigger-temp
