replicaCount: 1

image:
  repository: "#{dockerhub-user}#/#{image_name}#"
  pullPolicy: Always
  tag: "latest"

service:
  type: NodePort
  port: 30003
  nodePort: 30003

ingress:
  enabled: false

config:
  DEVICE_TYPE: "#{device_type}#"
  ES_INDEX: "#{es_index}#"

secrets:
  ES_USERNAME: "#{es-username}#"
  ES_PASSWORD: "#{es-password}#"
  TUYA_ACCESS_ID: "#{tuya-access-id}#"
  TUYA_ACCESS_KEY: "#{tuya-access-key}#"
  ES_HOST: "#{es_url}#"
  API_KEY: "#{api_key}#"
